#!/bin/bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
    items=$(find ~/Code/Herd -maxdepth 1 -mindepth 1 -type d ! -name ".flux")
    items=$(echo -e "$items\n$(find ~/bin -maxdepth 0)")
    # items=$(echo -e "$items\n$(find ~/Tmp -maxdepth 1 -mindepth 1 -type d)")
    selected=$(echo -e "$items" | fzf)
fi

dirname=$(basename $selected | sed 's/\./_/g')

if tmux has-session -t "$dirname" 2>/dev/null; then
    tmux switch-client -t "$dirname"
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname
